### ISSUE TITLE
Upgrade to python-irodsclient v3.3

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2253]
This has some breaking changes from v3.1 and before, at least the following:

```
ImportError: cannot import name 'UserGroup' from 'irods.models' (/opt/hostedtoolcache/Python/3.9.23/x64/lib/python3.9/site-packages/irods/models.py)
```

Because of this I'm breaking this off from #2232 into its own issue. Upgrading should be done with care and thoroughly tested.

There don't seem to be many major updates of interested here, apart from support for iRODS v5.x, which we won't be supporting at least before the release of v5.1 anyway. Hence, if this seems too much of a hassle it can be postponed.

## Tasks

- [x] Upgrade dependency
- [x] Fix `UserGroup` import
- [x] Fix `AVU value ('') is zero-length` errors
- [x] Ensure tests pass
- [x] Update docs

**Comment by mikkonie** [comment]
PRC v3.3 has been released, could try to see how that works. It would be nice to ensure we're in a current version before debugging #2471.

**Comment by mikkonie** [comment]
Trying this for v1.3.0. Let's see if feasible.

**Comment by mikkonie** [comment]
It appears some breaking change has been made to AVUs:

```
======================================================================
ERROR: test_get_stats_empty (irodsbackend.tests.test_api_taskflow.TestIrodsAPIGetStats.test_get_stats_empty)
Test get_stats() with no files
----------------------------------------------------------------------

(...)

taskflowbackend.api.TaskflowAPI.FlowSubmitException: Error running flow: AVU value ('') is zero-length.
```

Judging by debug logs, this seems to happen in `CreateUserGroupTask`. Let's see how we need to change the syntax..

**Update:** Well that was easy, simply rename the `user_groups` manager to `groups`.

**Comment by mikkonie** [comment]
Done.
