### ISSUE TITLE
Study shortcut retrieval error with unexpected characters in ISA-Tab name fields

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-server#2433]
Reported by @messersc. In production, we ran into an error where attempting to open study shortcuts for specific sample sheets fails with an error:

```
Error retrieving shortcut links: 'NoneType' object has no attribute 'study'
```

The sheets in question contain source and sample names with `+` in them. Intuition says this is due to us placing the IDs in the query string for the `StudyLinksAjaxView` URL. I guess we are not properly encoding the URL component before submission, resulting in a broken query. That's an obvious bug.

We should also consider which characters we want to support in node names and which not. The `+` character is supported by ISA-Tab, iRODS and (I guess) most file systems, but something like these kind of URL issues make it kind of un-safe IMHO.

In any case, this can be fixed and we can discuss setting down rules for valid name characters elsewhere.

We should also check for other places where we might be pushing source/sample/etc IDs directly into an URL query string. Tests need to also be updated to ensure expected behaviour.

I can make this into a v1.2.7 hotfix is necessary. I'd rather not tbh, as I just tagged v1.2.6 and going back to work on the ancient and out-of-date v1.2 branch is a pain.
